# image: docker:dind
image: archlinux:base-devel

stages:
  - test

before_script:
  - dockerd &
  - sleep 5
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - apt install -y make

test:
  stage: test
  tags:
    - docker
  script:
    - make install
  only:
    - /^main.*$/
