# dein.vim command
[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
source ~/.config/nvim/rc/vim-vue.vim
'''

[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "javascript", "rust"]
build = "./install_gadget.py --enable-python --force-enable-node --force-enable-rust"

