# dein.vim command
[[plugins]]
repo = 'haya14busa/dein-command.vim'
on_cmd = 'Dein'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#depends = 'context_filetype.vim'
#on_event = 'InsertEnter'
#hook_source = '''
#source ~/.config/nvim/rc/deoplete.vim
#'''

[[plugins]]
repo = 'Shougo/denite.nvim'
# on_event = 'BufRead'
hook_add = 'call hook#add#denite#load()'
hook_source = 'call hook#source#denite#load()'

