[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mattn/benchvimrc-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/rc/lightline.vim
'''

#[[plugins]]
#repo = 'maximbaz/lightline-ale'
#depends = ['lightline.vim', 'ale']
#hook_add = '''
#source ~/.config/nvim/rc/lightline-ale.vim
#'''

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# Golang
[[plugins]]
repo = 'fatih/vim-go'

# 関数内検索
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = ['vim-operator-user', 'vim-textobj-function', 'vim-textobj-user']
hook_add = '''
nmap <Space>/ <Plug>(operator-search)if
'''

# ale
#[[plugins]]
#repo = 'w0rp/ale'
#hook_add = '''
#source ~/.config/nvim/rc/ale.vim
#'''

# vim-table-mode
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# mattn/sonictemplate-vim
[[plugins]]
repo = 'mattn/sonictemplate-vim'

# reireias/vim-cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# simeji/winresizer
[[plugins]]
repo = 'simeji/winresizer'

# thinca/vim-quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

# tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'

# neoclide/coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# pangloss/vim-javascript
[[plugins]]
repo = 'pangloss/vim-javascript'

# moll/vim-node
[[plugins]]
repo = 'moll/vim-node'

#basyura/TweetVim
[[plugins]]
repo = 'basyura/TweetVim'

#mattn/webapi-vim
[[plugins]]
repo = 'mattn/webapi-vim'

#basyura/twibill.vim
[[plugins]]
repo = 'basyura/twibill.vim'

#tyru/open-browser.vim
[[plugins]]
repo = 'tyru/open-browser.vim'

#basyura/bitly.vim
[[plugins]]
repo = 'basyura/bitly.vim'

#terryma/vim-multiple-cursors
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

#Chiel92/vim-autoformat
[[plugins]]
repo = 'Chiel92/vim-autoformat'

#[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
#repo = 'osyo-manga/vim-precious'
#depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'skanehira/vsession'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'andymass/vim-matchup'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'thosakwe/vim-flutter'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'yuki-yano/fern-preview.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0

[[plugins]]
repo = 'akinsho/toggleterm.nvim'

[[plugins]]
repo = 'embear/vim-localvimrc'

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'preservim/vim-markdown'

