[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/rc/lightline.vim
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
source ~/.config/nvim/rc/lightline-ale.vim
'''

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# Golang
[[plugins]]
repo = 'fatih/vim-go'

# neoterm
[[plugins]]
repo = 'kassio/neoterm'
if = "has('nvim')"
hook_add = '''
nnoremap <silent> ,rc :TREPLSendFile<cr>
nnoremap <silent> ,rl :TREPLSendLine<cr>
vnoremap <silent> ,rl :TREPLSendSelection<cr>
nnoremap <silent> vt :Ttoggle<cr>
nnoremap <silent> vs :terminal<cr>
'''

# Vimfiler
[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nnoremap <silent> fb :<C-u>Unite buffer<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/rc/vimfiler.vim
'''

# 関数内検索
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = ['vim-operator-user', 'vim-textobj-function', 'vim-textobj-user']
hook_add = '''
nmap <Space>/ <Plug>(operator-search)if
'''

# ale
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/rc/ale.vim
'''

# vim-table-mode
[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

# mattn/sonictemplate-vim
[[plugins]]
repo = 'mattn/sonictemplate-vim'

# reireias/vim-cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'

# simeji/winresizer
[[plugins]]
repo = 'simeji/winresizer'

# thinca/vim-quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'

# tpope/vim-fugitive
[[plugins]]
repo = 'tpope/vim-fugitive'

# scrooloose/nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'

# autozimu/LanguageClinet-neovim
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

# pangloss/vim-javascript
[[plugins]]
repo = 'pangloss/vim-javascript'