# Sheldon configuration for zsh plugins
# Converted from zinit setup

shell = "zsh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.docker-completion]
github = "docker/cli"
dir = "contrib/completion/zsh"
use = ["_docker"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for plugin in plugins %}{{ plugin.raw }}{% endfor %}{{ hooks?.post | nl }}"